// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass HighlightedTextControlStyleDictionary : Windows.UI.Xaml.ResourceDictionary
    {
        HighlightedTextControlStyleDictionary();
    }
}
